/*
*
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMMMMMMM
MMMMMMMMMKc:xNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXo;lKMMMMMM
MMMMMMMMWO;  ,xNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXo. .cKMMMMMM
MMMMMMMMMMNk;  ,xNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKo. .:OWMMMMMMM
MMMMMMMMMMMMNk;  ,xNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKo. .c0WMMMMMMMMM
MMMMMMMMMMMMMMNk;  ,xNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKo. .c0WMMMMMMMMMMM
MMMMMMMMMMMMMMMMNk;  ,xNMMMMMMMMMMMMMMMMMMMMMMMMMKo. .c0WMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMNk;. 'dXMMMMMMMMMMMMMMMMMMMMWKo. .c0WMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMNk;  'dXMMMMMMMMMMMMMMMMWKl. .c0WMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMNk;. 'dXMMMMMMMMMMMMWKl. .c0WMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMNO;. 'dXMMMMMMMMWKl. .c0WMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMWO;. 'dXMMMMWKl. .c0WMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMWO;. 'd0K0l. .c0WMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO:. ... .l0WMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0,     :XMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0l. .,:;. 'dXMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMW0l. .lKWWWO:. 'dXMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMW0c. .lKWMMMMMWO:. .dXMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMW0c. .lKWMMMMMMMMMWO:. .oXMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMW0c. .lKWMMMMMMMMMMMMMWO:. .oXMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMW0c. .lKWMMMMMMMMMMMMMMMMMWO:. .oXMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMW0c. .lKWMMMMMMMMMMMMMMMMMMMMMWO:. .oKMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMW0c. .oKMMMMMMMMMMMMMMMMMMMMMMMMMMW0:. .oKMMMMMMMMMMMMM
MMMMMMMMMMMMMW0c. .oKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0c. .oKMMMMMMMMMMM
MMMMMMMMMMMW0c. .oKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0c. .oKMMMMMMMMM
MMMMMMMMMW0c. .oKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0c. .lKMMMMMMM
MMMMMMMMMO. .oKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0c. ;KMMMMMM
MMMMMMMMMNOxKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0d0WMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
* */

import React, { PureComponent } from "react";
import Icon from "./Icon";
import PropTypes from "prop-types";

@Icon
class CloseIcon extends PureComponent {
    render() {
        const { color, opacity } = this.props;

        return (
            <svg
                width="16"
                height="16"
                viewBox="0 0 16 16"
                fill={color}
                fillOpacity={opacity}
            >
                <path d="M15.9867 15.381L0.61496 0.00927734L9.01424e-05 0.624147L15.3718 15.9959L15.9867 15.381Z" />
                <path d="M15.3811 9.05409e-05L0.00933838 15.3718L0.624208 15.9867L15.9959 0.61496L15.3811 9.05409e-05Z" />
            </svg>
        );
    }
}

CloseIcon.propTypes = {
    color: PropTypes.string,
    opacity: PropTypes.number,
};
export default CloseIcon;
