/*
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0do0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO'  'kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx.    .dNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo.      .cXMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMXc          ;KWMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMK;            'OWMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMWO'              .xNMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMWWXKOxdlc;.                 ,ccoxO0KNWMMMMMMMMMMMMMMMM
MMMMMMMMMWKOxdlc:,..                              ..',:coxk0NMMMMMMMMM
MMMMMMMMMNx'                                              .xNMMMMMMMMM
MMMMMMMMMMMKo.                                          .cKWMMMMMMMMMM
MMMMMMMMMMMMWO;                                        ;kNMMMMMMMMMMMM
MMMMMMMMMMMMMMNk;                                    ,kNMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMNk'                                .oXMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMXo.                            .lKWMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMWx.                           :NMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMWl                            :NMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMN:                            ,KMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMX:                            .kMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMM0'             ..             .xMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMx.        .':ok00Odc,.         lWMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMx.    .;lx0NMMMMMMMMNKOo:'.    :XMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMWo.,cdOXWMMMMMMMMMMMMMMMMMNKxl;.cXMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMWXKNMMMMMMMMMMMMMMMMMMMMMMMMMMWXXWMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
* */

import React, { PureComponent } from "react";
import Icon from "./Icon";
import PropTypes from "prop-types";

@Icon
class StarIconFilled extends PureComponent {
    render() {
        const { color } = this.props;

        return (
            <svg width="15" height="14" viewBox="0 0 15 14" fill="none">
                <path
                    fill={color}
                    d="M10.0943 4.25551L15 5.3348L11.6981 9.06608L12.1698 14L7.51572 12.0264L2.89308 14L3.33333 9.06608L0 5.36564L4.93711 4.25551L7.48428 0L10.0943 4.25551Z"
                />
            </svg>
        );
    }
}

StarIconFilled.propTypes = {
    color: PropTypes.string,
};
export default StarIconFilled;
